title: 働き爪
author: Working Nail
description: A site for deep nail healing
baseurl: "" # サブディレクトリなしなら空欄でOK
url: "https://workingnail.github.io" # 必ずあなたのGitHub Pages URLに変更

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - screenshot.png
  - CHANGELOG.md
  - docs/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: null
  -
    scope:
      path: ""
    values:
      layout: null
