title: 働き爪
author: Working Nail
baseurl: ""

navbar-links:
  応援ページ: "aboutme"
  ブログ一覧: "index"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

social-network-links:
  email: "someone@example.com"
  rss: true
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: "@daattali"
  whatsapp: 15551212

rss-description: This website is a virtual proof that I'm awesome

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  reddit: false

url-pretty: "MyWebsite.com"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer
